apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  namespace: devops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0-jre11-slim
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: code-volume # Name of the volume mount
          mountPath: /usr/local/tomcat/webapps/ROOT/shop.jsp # Exact file path in container
          subPath: shop.jsp # Name of the key in the ConfigMap
      volumes:
      - name: code-volume # Matches the name used in volumeMounts
        configMap:
          name: ecommerce-logic # Name of the ConfigMap created by the workflow
