apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: devops-lab
data:
  default.conf: |
    server {
        listen 80;
        location / {
            # Pass to the Tomcat application service name
            proxy_pass http://app-server:8080/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
